package com.knowledgeSupport.api.adapter.in.web;

import com.knowledgeSupport.api.domain.model.Standard;
import com.knowledgeSupport.api.domain.model.enums.IncidentType;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.UUID;

@Schema(description = "Error pattern registered in the knowledge base")
public record StandardResponse(

        @Schema(description = "Unique identifier generated by the system",
                example = "3f2c9a1e-8b4d-4e2a-9c7f-1a2b3c4d5e6f")
        UUID id,

        @Schema(description = "Short name identifying the pattern", example = "HUB login permission")
        String standardName,

        @Schema(description = "Description of the error/symptom", example = "User with buyer profile can't log into the HUB")
        String text,

        @Schema(description = "Standard solution", example = "Add the BUYER profile in the user's access screen")
        String result,

        @Schema(description = "Incident type", example = "ERROR")
        IncidentType incidentType,

        @Schema(description = "WINTHOR routine number (optional)", example = "1234")
        Integer routineNumber
) {
    public static StandardResponse from(Standard standard) {
        return new StandardResponse(standard.getId(), standard.getStandardName(), standard.getText(), standard.getResult(), standard.getIncidentType(), standard.getRoutineNumber());
    }
}
